image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

version:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - "#!/bin/bash"
    - export MOD_VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2)
    - IFS='.' read -r v1 v2 v3 <<< "$MOD_VERSION"
    - export NEW_MOD_VERSION="$v1.$v2.$((v3+1))"
    - echo "MOD_VERSION=${NEW_MOD_VERSION}" >> version.env
    - echo "OLD_VERSION=${MOD_VERSION}" >> version.env
  artifacts:
    reports:
        dotenv: version.env
jar:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: version
      artifacts: true
  script:
    - sed -i "s/mod_version=$OLD_VERSION/mod_version=$MOD_VERSION/g" gradle.properties
    - gradle jar
    - mv build/reobfJar/output.jar crinklemod-$MOD_VERSION.jar
    - echo "JAR_JOB_ID=${CI_JOB_ID}" >> variables.env
  cache:
      key: "$CI_COMMIT_REF_NAME"
      policy: push
      paths:
      - build
      - .gradle
  artifacts:
    paths:
      - crinklemod-$MOD_VERSION.jar
    expire_in: 12 months
    name: "crinklemod-$MOD_VERSION.jar"
    reports:
      dotenv: variables.env


commit_version:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: version
      artifacts: true
    - job: jar
      artifacts: true
  script:
    - sed -i "s/mod_version=$OLD_VERSION/mod_version=$MOD_VERSION/g" gradle.properties
    - git config --global user.name "GitLab CI"
    - git config --global user.email "fuzzy.little.devil+ci@gmail.com"
    - git config --global url.https://.insteadOf git://
    - git remote set-url origin https://${GITLAB_CI_USER}:${GITLAB_CI_TOKEN}@gitlab.com/fuzzy.little.devil/crinklemod.git
    - git add gradle.properties
    - git commit -m "[skip ci] Bump version to $MOD_VERSION"
    - git push -u origin HEAD:main

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Releasing CrinkleMod v$MOD_VERSION"
  needs:
    - job: version
      artifacts: true
    - job: jar
      artifacts: true
    - job: commit_version
  release:
    name: "CrinkleMod v$MOD_VERSION"
    tag_name: "v$MOD_VERSION"
    description: "CrinkleMod v$MOD_VERSION"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "CrinkleMod v$MOD_VERSION Jar"
          url: "https://gitlab.com/fuzzy.little.devil/crinklemod/-/jobs/${JAR_JOB_ID}/artifacts/file/crinklemod-$MOD_VERSION.jar"
