image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

jar:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - export MOD_VERSION=$(grep mod_version gradle.properties | cut -d'=' -f2)
    - IFS='.' read -r v1 v2 v3 <<< "$MOD_VERSION"
    - export NEW_MOD_VERSION="$v1.$v2.$((v3+1))"
    - sed -i "s/mod_version=$MOD_VERSION/mod_version=$NEW_MOD_VERSION/g" gradle.properties
  script:
    - gradle jar
    - mv build/reobfJar/output.jar crinklemod-$CI_COMMIT_SHORT_SHA.jar
    - echo "JAR_JOB_ID=${CI_JOB_ID}" >> variables.env
    - echo "MOD_VERSION=${NEW_MOD_VERSION}" >> variables.env
  after_script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "fuzzy.little.devil@gmail.com"
    - git add gradle.properties
    - git commit -m "Bump version to $NEW_MOD_VERSION"
    - git push -o ci.skip "https://${GITLAB_CI_USER}:${GITLAB_CI_TOKEN}@${CI_REPOSITORY_URL#*@}" HEAD:main
  cache:
      key: "$CI_COMMIT_REF_NAME"
      policy: push
      paths:
      - build
      - .gradle
  artifacts:
    paths:
      - crinklemod-$CI_COMMIT_SHORT_SHA.jar
    expire_in: 12 months
    name: "crinklemod-$CI_COMMIT_SHORT_SHA.jar"
    reports:
      dotenv: variables.env

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Releasing CrinkleMod v$MOD_VERSION"
  needs:
    - job: jar
      artifacts: true
  release:
    name: "CrinkleMod v$MOD_VERSION"
    tag_name: "v$MOD_VERSION"
    description: "CrinkleMod v$MOD_VERSION"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "CrinkleMod v$MOD_VERSION Jar"
          url: "https://gitlab.com/fuzzy.little.devil/crinklemod/-/jobs/${JAR_JOB_ID}/artifacts/file/crinklemod-$MOD_VERSION.jar"


