image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

jar:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - gradle jar
    - mv build/reobfJar/output.jar crinklemod-$CI_COMMIT_SHORT_SHA.jar
    - echo "JAR_JOB_ID=${CI_JOB_ID}" >> variables.env
  cache:
      key: "$CI_COMMIT_REF_NAME"
      policy: push
      paths:
      - build
      - .gradle
  artifacts:
    paths:
      - crinklemod-$CI_COMMIT_SHORT_SHA.jar
    expire_in: 12 months
    name: "crinklemod-$CI_COMMIT_SHORT_SHA.jar"
    reports:
      dotenv: variables.env

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Releasing Latest"
  needs:
    - job: jar
      artifacts: true
  release:
    name: "CrinkleMod Latest"
    tag_name: "latest"
    description: "CrinkleMod Latest"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "CrinkleMod Latest Jar"
          url: "https://gitlab.com/fuzzy.little.devil/crinklemod/-/jobs/${JAR_JOB_ID}/artifacts/file/crinklemod-$CI_COMMIT_SHORT_SHA.jar"


